import type { AnimeSummary } from "../types/anime";

export const fixedAnime: AnimeSummary[] = [
  { mal_id: 5114, title: "Fullmetal Alchemist: Brotherhood", image_url: "https://myanimelist.net/images/anime/1208/94745l.jpg", total_episodes: 64, genres: ["Action", "Adventure", "Drama", "Fantasy"], studios: ["Bones"], platforms: ["Crunchyroll", "Hulu"], year: 2009, score: 9.1, synopsis: "Two brothers search for a way to restore what alchemy took from them, crossing a country built on secrets." },
  { mal_id: 9253, title: "Steins;Gate", image_url: "https://myanimelist.net/images/anime/1935/127974l.jpg", total_episodes: 24, genres: ["Drama", "Sci-Fi", "Suspense"], studios: ["White Fox"], platforms: ["Crunchyroll", "Hulu"], year: 2011, score: 9.0, synopsis: "A small lab stumbles into time travel and learns how cruel cause and effect can become." },
  { mal_id: 28977, title: "Gintama", image_url: "https://myanimelist.net/images/anime/3/72078l.jpg", total_episodes: 51, genres: ["Action", "Comedy", "Sci-Fi"], studios: ["Bandai Namco Pictures"], platforms: ["Crunchyroll"], year: 2015, score: 9.0, synopsis: "Odd jobs, samurai chaos, parody, and sudden emotional gut punches in an alien-occupied Edo." },
  { mal_id: 11061, title: "Hunter x Hunter", image_url: "https://myanimelist.net/images/anime/1337/99013l.jpg", total_episodes: 148, genres: ["Action", "Adventure", "Fantasy"], studios: ["Madhouse"], platforms: ["Crunchyroll", "Netflix", "Hulu"], year: 2011, score: 9.0, synopsis: "A bright young hunter enters a world of monsters, tests, friendships, and terrifying ambition." },
  { mal_id: 38524, title: "Attack on Titan Season 3 Part 2", image_url: "https://myanimelist.net/images/anime/1517/100633l.jpg", total_episodes: 10, genres: ["Action", "Drama", "Suspense"], studios: ["Wit Studio"], platforms: ["Crunchyroll", "Hulu"], year: 2019, score: 9.0, synopsis: "Humanity reaches the basement and the story opens into something far larger and harsher." },
  { mal_id: 52991, title: "Sousou no Frieren", image_url: "https://myanimelist.net/images/anime/1015/138006l.jpg", total_episodes: 28, genres: ["Adventure", "Drama", "Fantasy"], studios: ["Madhouse"], platforms: ["Crunchyroll"], year: 2023, score: 9.3, synopsis: "An elf mage retraces an old journey and slowly understands the people she outlived." },
  { mal_id: 32281, title: "Kimi no Na wa.", image_url: "https://myanimelist.net/images/anime/5/87048l.jpg", total_episodes: 1, genres: ["Drama", "Romance", "Supernatural"], studios: ["CoMix Wave Films"], platforms: ["Crunchyroll"], year: 2016, score: 8.8, synopsis: "Two strangers swap lives across distance and disaster, chasing a connection neither can explain." },
  { mal_id: 199, title: "Sen to Chihiro no Kamikakushi", image_url: "https://myanimelist.net/images/anime/6/79597l.jpg", total_episodes: 1, genres: ["Adventure", "Fantasy", "Supernatural"], studios: ["Studio Ghibli"], platforms: ["Max"], year: 2001, score: 8.8, synopsis: "A lost girl works in a bathhouse for spirits and finds courage one impossible task at a time." },
  { mal_id: 1535, title: "Death Note", image_url: "https://myanimelist.net/images/anime/1079/138100l.jpg", total_episodes: 37, genres: ["Supernatural", "Suspense"], studios: ["Madhouse"], platforms: ["Netflix", "Hulu"], year: 2006, score: 8.6, synopsis: "A brilliant student gains a notebook that kills and begins a battle of justice, ego, and deduction." },
  { mal_id: 21, title: "One Piece", image_url: "https://myanimelist.net/images/anime/1244/138851l.jpg", total_episodes: 0, genres: ["Action", "Adventure", "Fantasy"], studios: ["Toei Animation"], platforms: ["Crunchyroll", "Netflix", "Hulu"], year: 1999, score: 8.7, synopsis: "A rubber pirate and his crew sail for the ultimate treasure through a world of dreams and tyrants." },
  { mal_id: 16498, title: "Shingeki no Kyojin", image_url: "https://myanimelist.net/images/anime/10/47347l.jpg", total_episodes: 25, genres: ["Action", "Drama", "Suspense"], studios: ["Wit Studio"], platforms: ["Crunchyroll", "Hulu"], year: 2013, score: 8.5, synopsis: "People trapped behind walls face titans outside and truths inside." },
  { mal_id: 38000, title: "Kimetsu no Yaiba", image_url: "https://myanimelist.net/images/anime/1286/99889l.jpg", total_episodes: 26, genres: ["Action", "Fantasy"], studios: ["ufotable"], platforms: ["Crunchyroll", "Netflix", "Hulu"], year: 2019, score: 8.5, synopsis: "A kind boy becomes a demon slayer to save his sister and avenge his family." },
  { mal_id: 40748, title: "Jujutsu Kaisen", image_url: "https://myanimelist.net/images/anime/1171/109222l.jpg", total_episodes: 24, genres: ["Action", "Supernatural"], studios: ["MAPPA"], platforms: ["Crunchyroll", "Netflix"], year: 2020, score: 8.6, synopsis: "A teenager swallows a curse and enters a brutal school for sorcerers." },
  { mal_id: 31964, title: "Boku no Hero Academia", image_url: "https://myanimelist.net/images/anime/10/78745l.jpg", total_episodes: 13, genres: ["Action"], studios: ["Bones"], platforms: ["Crunchyroll", "Hulu", "Netflix"], year: 2016, score: 7.9, synopsis: "A powerless boy in a superpowered society gets his chance to become a hero." },
  { mal_id: 30276, title: "One Punch Man", image_url: "https://myanimelist.net/images/anime/12/76049l.jpg", total_episodes: 12, genres: ["Action", "Comedy"], studios: ["Madhouse"], platforms: ["Crunchyroll", "Hulu", "Netflix"], year: 2015, score: 8.5, synopsis: "A hero who wins every fight with one punch searches for meaning beyond strength." },
  { mal_id: 20583, title: "Haikyuu!!", image_url: "https://myanimelist.net/images/anime/7/76014l.jpg", total_episodes: 25, genres: ["Sports"], studios: ["Production I.G"], platforms: ["Crunchyroll", "Netflix", "Hulu"], year: 2014, score: 8.4, synopsis: "A small but explosive volleyball player finds a team that can make him fly." },
  { mal_id: 245, title: "Great Teacher Onizuka", image_url: "https://myanimelist.net/images/anime/13/11460l.jpg", total_episodes: 43, genres: ["Comedy", "Drama"], studios: ["Pierrot"], platforms: ["Crunchyroll"], year: 1999, score: 8.7, synopsis: "A former delinquent becomes a teacher and reaches students through chaos and heart." },
  { mal_id: 1, title: "Cowboy Bebop", image_url: "https://myanimelist.net/images/anime/4/19644l.jpg", total_episodes: 26, genres: ["Action", "Sci-Fi"], studios: ["Sunrise"], platforms: ["Crunchyroll", "Hulu", "Netflix"], year: 1998, score: 8.8, synopsis: "Bounty hunters drift through space, chasing criminals and the pasts they cannot outrun." },
  { mal_id: 30, title: "Neon Genesis Evangelion", image_url: "https://myanimelist.net/images/anime/1314/108941l.jpg", total_episodes: 26, genres: ["Action", "Drama", "Sci-Fi"], studios: ["Gainax"], platforms: ["Netflix"], year: 1995, score: 8.4, synopsis: "Teen pilots fight giant beings while the adults around them hide the real shape of the war." },
  { mal_id: 6547, title: "Angel Beats!", image_url: "https://myanimelist.net/images/anime/1244/111115l.jpg", total_episodes: 13, genres: ["Drama", "Supernatural"], studios: ["P.A. Works"], platforms: ["Crunchyroll"], year: 2010, score: 8.0, synopsis: "Teens in an afterlife school rebel, joke, and slowly face what kept them there." },
  { mal_id: 1575, title: "Code Geass", image_url: "https://myanimelist.net/images/anime/1032/135088l.jpg", total_episodes: 25, genres: ["Action", "Drama", "Sci-Fi"], studios: ["Sunrise"], platforms: ["Crunchyroll", "Hulu"], year: 2006, score: 8.7, synopsis: "A prince with mind-control power wages rebellion through strategy, masks, and sacrifice." },
  { mal_id: 2001, title: "Tengen Toppa Gurren Lagann", image_url: "https://myanimelist.net/images/anime/4/5123l.jpg", total_episodes: 27, genres: ["Action", "Adventure", "Sci-Fi"], studios: ["Gainax"], platforms: ["Crunchyroll", "Hulu"], year: 2007, score: 8.6, synopsis: "A boy digs upward from underground into a universe-sized fight for freedom." },
  { mal_id: 11741, title: "Fate/Zero", image_url: "https://myanimelist.net/images/anime/1522/117645l.jpg", total_episodes: 13, genres: ["Action", "Fantasy", "Supernatural"], studios: ["ufotable"], platforms: ["Crunchyroll", "Hulu"], year: 2011, score: 8.3, synopsis: "Mages and heroic spirits fight a cruel war where every wish has a cost." },
  { mal_id: 31240, title: "Re:Zero", image_url: "https://myanimelist.net/images/anime/1522/128039l.jpg", total_episodes: 25, genres: ["Drama", "Fantasy", "Suspense"], studios: ["White Fox"], platforms: ["Crunchyroll"], year: 2016, score: 8.2, synopsis: "A boy trapped in another world survives by dying, remembering, and trying again." },
  { mal_id: 13601, title: "Psycho-Pass", image_url: "https://myanimelist.net/images/anime/1314/142015l.jpg", total_episodes: 22, genres: ["Action", "Sci-Fi", "Suspense"], studios: ["Production I.G"], platforms: ["Crunchyroll", "Hulu"], year: 2012, score: 8.3, synopsis: "Inspectors police a society that measures criminal potential before crimes happen." },
  { mal_id: 22199, title: "Akame ga Kill!", image_url: "https://myanimelist.net/images/anime/1429/95946l.jpg", total_episodes: 24, genres: ["Action", "Fantasy"], studios: ["White Fox"], platforms: ["Hulu"], year: 2014, score: 7.5, synopsis: "Assassins strike back against a corrupt empire in a story that refuses easy comfort." },
  { mal_id: 23273, title: "Shigatsu wa Kimi no Uso", image_url: "https://myanimelist.net/images/anime/1405/143284l.jpg", total_episodes: 22, genres: ["Drama", "Romance"], studios: ["A-1 Pictures"], platforms: ["Crunchyroll", "Netflix", "Hulu"], year: 2014, score: 8.6, synopsis: "A pianist who lost his sound meets a violinist who pulls him back toward music and grief." },
  { mal_id: 1735, title: "Naruto: Shippuuden", image_url: "https://myanimelist.net/images/anime/1565/111305l.jpg", total_episodes: 500, genres: ["Action", "Adventure", "Fantasy"], studios: ["Pierrot"], platforms: ["Crunchyroll", "Hulu"], year: 2007, score: 8.3, synopsis: "Naruto returns older, louder, and closer to the heavy truths of the ninja world." },
  { mal_id: 20, title: "Naruto", image_url: "https://myanimelist.net/images/anime/1141/142503l.jpg", total_episodes: 220, genres: ["Action", "Adventure", "Fantasy"], studios: ["Pierrot"], platforms: ["Crunchyroll", "Netflix", "Hulu"], year: 2002, score: 8.0, synopsis: "A lonely ninja kid chases recognition, friendship, and the dream of becoming Hokage." },
  { mal_id: 269, title: "Bleach", image_url: "https://myanimelist.net/images/anime/1541/147774l.jpg", total_episodes: 366, genres: ["Action", "Adventure", "Supernatural"], studios: ["Pierrot"], platforms: ["Hulu"], year: 2004, score: 7.9, synopsis: "A teenager becomes a soul reaper and steps into battles between worlds." }
];

export const platformOptions = ["Crunchyroll", "Netflix", "Hulu", "Max"];
