import type { MangaSummary } from "../types/anime";

export const fixedManhwa: MangaSummary[] = [
  { mal_id: 117465, title: "Na Honjaman Level Up", image_url: "https://cdn.myanimelist.net/images/manga/3/222295l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Action", "Adventure", "Fantasy"], authors: ["Chugong"], score: 8.6, year: 2018, synopsis: "The weakest hunter becomes humanity's last hope after a mysterious leveling system appears.", mediaType: "manhwa" },
  { mal_id: 102346, title: "Kami no Tou", image_url: "https://cdn.myanimelist.net/images/manga/2/189329l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Action", "Adventure", "Drama", "Fantasy", "Mystery"], authors: ["SIU"], score: 8.5, year: 2010, synopsis: "A boy climbs a tower to reunite with a friend and uncover the truth behind the world above.", mediaType: "manhwa" },
  { mal_id: 147506, title: "Omniscient Reader's Viewpoint", image_url: "https://cdn.myanimelist.net/images/manga/2/258749l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Action", "Adventure", "Drama", "Fantasy"], authors: ["sing N song"], score: 8.7, year: 2020, synopsis: "A reader becomes the only person who knows how the apocalypse will unfold.", mediaType: "manhwa" },
  { mal_id: 121496, title: "The Beginning After the End", image_url: "https://cdn.myanimelist.net/images/manga/1/226234l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Action", "Adventure", "Fantasy"], authors: ["TurtleMe"], score: 8.4, year: 2018, synopsis: "A king reborn into a world of magic tries to live better than his past life.", mediaType: "manhwa" },
  { mal_id: 121774, title: "Lookism", image_url: "https://cdn.myanimelist.net/images/manga/3/234711l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Action", "Comedy", "Drama"], authors: ["Park Tae-joon"], score: 8.2, year: 2019, synopsis: "A bullied teen wakes up in a handsome body and sees how society treats him differently.", mediaType: "manhwa" },
  { mal_id: 128496, title: "Nano Machine", image_url: "https://cdn.myanimelist.net/images/manga/2/269184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Action", "Adventure", "Fantasy", "Martial Arts"], authors: ["Hanjoong Wolya"], score: 8.1, year: 2020, synopsis: "A despised illegitimate son receives a future nano-technology implant that changes his fate.", mediaType: "manhwa" },
  { mal_id: 133445, title: "Return of the Mount Hua Sect", image_url: "https://cdn.myanimelist.net/images/manga/2/283184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Action", "Adventure", "Fantasy", "Martial Arts"], authors: ["Biga"], score: 8.3, year: 2021, synopsis: "A martial artist returns to his sect after dying and vows to protect it properly this time.", mediaType: "manhwa" },
  { mal_id: 128016, title: "Eleceed", image_url: "https://cdn.myanimelist.net/images/manga/2/270184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Action", "Comedy", "Supernatural"], authors: ["Son Jeho"], score: 8.0, year: 2020, synopsis: "A kind-hearted cat lover gains electric powers and stumbles into a hidden world of awakeners.", mediaType: "manhwa" },
  { mal_id: 114745, title: "True Beauty", image_url: "https://cdn.myanimelist.net/images/manga/1/224184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Comedy", "Drama", "Romance"], authors: ["Yaongyi"], score: 7.8, year: 2018, synopsis: "A girl masters makeup to hide her insecurities and navigates high school romance.", mediaType: "manhwa" },
  { mal_id: 85781, title: "The God of High School", image_url: "https://cdn.myanimelist.net/images/manga/2/173184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Action", "Comedy", "Fantasy", "Martial Arts"], authors: ["Yongje Park"], score: 7.9, year: 2011, synopsis: "Fighters compete in a tournament where the prize is any wish they desire.", mediaType: "manhwa" },
  { mal_id: 136946, title: "Villain to Kill", image_url: "https://cdn.myanimelist.net/images/manga/1/267184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Action", "Fantasy", "Supernatural"], authors: ["Jeon Sun-Young"], score: 8.0, year: 2021, synopsis: "A hero is reborn in the body of a villain and tries to survive in a darker world.", mediaType: "manhwa" },
  { mal_id: 132711, title: "Wind Breaker", image_url: "https://cdn.myanimelist.net/images/manga/3/271184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Action", "Sports"], authors: ["Yongseok Jo"], score: 8.2, year: 2021, synopsis: "A talented cyclist joins a high school biking crew built on loyalty and street racing.", mediaType: "manhwa" }
];

export const fixedLightNovels: MangaSummary[] = [
  { mal_id: 70287, title: "Mushoku Tensei: Isekai Ittara Honki Dasu", image_url: "https://cdn.myanimelist.net/images/manga/1/178184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Adventure", "Drama", "Fantasy"], authors: ["Rifujin na Magonote"], score: 8.5, year: 2014, synopsis: "A regretful man is reborn in a fantasy world and vows to live without repeating his mistakes.", mediaType: "light-novel" },
  { mal_id: 11813, title: "Re:Zero kara Hajimeru Isekai Seikatsu", image_url: "https://cdn.myanimelist.net/images/manga/2/178184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Drama", "Fantasy", "Suspense"], authors: ["Tappei Nagatsuki"], score: 8.4, year: 2014, synopsis: "A boy trapped in another world survives by dying, remembering, and trying again.", mediaType: "light-novel" },
  { mal_id: 11357, title: "Sword Art Online", image_url: "https://cdn.myanimelist.net/images/manga/1/178184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Action", "Adventure", "Fantasy", "Romance"], authors: ["Reki Kawahara"], score: 7.8, year: 2009, synopsis: "Players trapped in a VRMMO must clear the game or die for real.", mediaType: "light-novel" },
  { mal_id: 81667, title: "Overlord", image_url: "https://cdn.myanimelist.net/images/manga/2/178184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Action", "Adventure", "Fantasy"], authors: ["Kugane Maruyama"], score: 8.2, year: 2012, synopsis: "A gamer becomes his undead villain character when his MMO servers shut down.", mediaType: "light-novel" },
  { mal_id: 85781, title: "Kono Subarashii Sekai ni Shukufuku wo!", image_url: "https://cdn.myanimelist.net/images/manga/3/178184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Adventure", "Comedy", "Fantasy"], authors: ["Natsume Akatsuki"], score: 8.1, year: 2013, synopsis: "A useless hero and his dysfunctional party bumble through a fantasy world.", mediaType: "light-novel" },
  { mal_id: 48397, title: "No Game No Life", image_url: "https://cdn.myanimelist.net/images/manga/1/178184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Comedy", "Ecchi", "Fantasy"], authors: ["Yuu Kamiya"], score: 8.0, year: 2012, synopsis: "Sibling gamers are summoned to a world where every conflict is decided by games.", mediaType: "light-novel" },
  { mal_id: 5338, title: "Spice and Wolf", image_url: "https://cdn.myanimelist.net/images/manga/2/178184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Adventure", "Drama", "Fantasy", "Romance"], authors: ["Isuna Hasekura"], score: 8.3, year: 2006, synopsis: "A traveling merchant partners with a wolf deity on a journey of trade and trust.", mediaType: "light-novel" },
  { mal_id: 87609, title: "Tensei shitara Slime Datta Ken", image_url: "https://cdn.myanimelist.net/images/manga/3/178184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Action", "Adventure", "Comedy", "Fantasy"], authors: ["Fuse"], score: 8.0, year: 2014, synopsis: "A man reincarnates as a slime and builds a nation of monsters.", mediaType: "light-novel" },
  { mal_id: 90240, title: "Kusuriya no Hitorigoto", image_url: "https://cdn.myanimelist.net/images/manga/1/178184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Drama", "Mystery"], authors: ["Natsu Hyuuga"], score: 8.6, year: 2014, synopsis: "A palace pharmacist uses medicine and deduction to solve court mysteries.", mediaType: "light-novel" },
  { mal_id: 96792, title: "Tate no Yuusha no Nariagari", image_url: "https://cdn.myanimelist.net/images/manga/2/178184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Action", "Adventure", "Drama", "Fantasy"], authors: ["Aneko Yusagi"], score: 7.9, year: 2013, synopsis: "A summoned hero is betrayed and must survive with only a shield.", mediaType: "light-novel" },
  { mal_id: 55265, title: "Monogatari Series: First Season", image_url: "https://cdn.myanimelist.net/images/manga/3/178184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Comedy", "Mystery", "Romance", "Supernatural"], authors: ["Nisio Isin"], score: 8.4, year: 2006, synopsis: "A boy helps classmates afflicted by supernatural oddities one arc at a time.", mediaType: "light-novel" },
  { mal_id: 122558, title: "Sousou no Frieren", image_url: "https://cdn.myanimelist.net/images/manga/1/178184l.jpg", total_chapters: 0, total_volumes: 0, genres: ["Adventure", "Drama", "Fantasy"], authors: ["Kanehito Yamada"], score: 9.0, year: 2020, synopsis: "An elf mage retraces an old journey and slowly understands the people she outlived.", mediaType: "light-novel" }
];
